#pragma once

#include "../GameInfo.h"

enum class EEventType : unsigned char
{
	GOTO_MENU_SCENE,
	GOTO_PLAY_SCENE,
	GOTO_RESULT_SCENE,

	GOTO_PLAY_SUB_STATE_PLAY,
	GOTO_PLAY_SUB_STATE_PAUSE,
	GOTO_PLAY_SUB_STATE_LVLUP,
	GOTO_PLAY_SUB_STATE_GAMEOVER,

	PLAYER_HP_CHANGED,
	PLAYER_EXP_GAINED,
	PLAYER_LEVEL_UP_BEGIN,
	PLAYER_LEVEL_UP_CHOICE,
	PLAYER_LEVEL_UP_SELECT,

	REGULAR_MOB_SPAWN,
	SUBBOSS_MOB_SPAWN,

	MAX
};